---
- name: Deploy Python App from Zip Archive (Simple)
  hosts: web
  become: true
  become_user: ubuntu

  tasks:
    - name: Download ZIP from Nexus
      get_url:
        url: http://52.14.130.215:8081/repository/maven-releases/cart.zip
        dest: /home/ubuntu/cart.zip

    - name: Unzip app package
      unarchive:
        src: /home/ubuntu/cart.zip
        dest: /home/ubuntu/cart
        remote_src: yes

    - name: Install required packages (system-wide)
      apt:
        name:
          - python3
          - python3-pip
        update_cache: yes

    - name: Install requirements
      pip:
        requirements: /home/ubuntu/cart/requirements.txt

    - name: Run Python app in background
      shell: nohup python3 app.py > output.log 2>&1 &
      args:
        chdir: /home/ubuntu/cart
