---
- name: Deploy Python App from Zip Archive (Simple)
  hosts: web
  become: true
  become_user: ubuntu

  tasks:
    - name: Download ZIP from Nexus
      ansible.builtin.get_url:
        url: http://52.14.130.215:8081/repository/maven-releases/cart.zip
        dest: /home/ubuntu/cart.zip

    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: /home/ubuntu/cart
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Unzip app package
      ansible.builtin.unarchive:
        src: /home/ubuntu/cart.zip
        dest: /home/ubuntu/cart
        remote_src: yes

    - name: Run Python app in background
      ansible.builtin.shell: nohup python3 app.py > output.log 2>&1 &
      args:
        chdir: /home/ubuntu/cart
